baseURL: "https://vasavamsi.netlify.app/"
languageCode: en-us
title: Vamsi Krishna Vasa
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Publications
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Vamsi Krishna Vasa"
    subtitle: |
      Hi there! 👋 I'm Vamsi, a machine learning maestro with a knack for turning data into insights. As a Graduate Student Researcher at <a href="https://acims.asu.edu/" style="color: orange;">ASIMS</a> Lab, ASU, I'm working on Thesis to push the boundaries of AI by teaching them to mimic the real world assembly line industries, such as semiconductor manufacturing. My Research work is supervised by <a href="https://search.asu.edu/profile/333046" style="color:orange;">Dr. Hessam Sarjoughian</a> and is supported by <a href="https://www.intel.com/content/www/us/en/research/overview.html" style="color: orange;">Intel Labs</a>.
      
      I got immense experience With a toolbox full of Python, AWS, and an array of ML libraries, I'm always ready to tackle the next exciting challenge in Computer Vision, Time Series analytics or Natural Language Processing. Whether it's leveraging GenAI to aid healthcare diagnostics or simulate the real world scenarios, I am all in!
      
      Let's connect and explore how we can leverage AI to make a real-world impact. Who knows? We might just train a model that changes the game! 🚀
 
    imageUrl: "home/propic.jpg"
    imageWidth: 220
    imageHeight: 220 
    buttons:
      - name: Resume
        url: "https://drive.google.com/file/d/1zScAnJj9IiHVPjov5urLIDTV9WyU2gA6/view?usp=sharing"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:vvasa1@asu.edu"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/vasa-vamsi-krishna"
    - name: "github"
      url: "https://github.com/vasavamsi"
    - name: "google-scholar"
      url: "https://scholar.google.com/citations?hl=en&user=4-jHQiIAAAAJ"
      icon: "fa fa-google"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
