baseURL: "https://vasavamsi.netlify.app/"
languageCode: en-us
title: Vamsi Krishna Vasa
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Publications
      url: /blog
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Vamsi Krishna Vasa"
    subtitle: |
      Hello! I'm Vamsi, a Graduate Student Researcher at the <a href="https://acims.asu.edu/" style="color: orange;">ACIMS Lab</a> at Arizona State University, where I am pursuing my Master’s thesis under the guidance of <a href="https://search.asu.edu/profile/333046" style="color:orange;">Dr. Hessam Sarjoughian</a>. My research focuses on Behavior Modeling of the System Components and auto-code generation for Discrete Event Simulations using Generative AI. This work is being conducted in collaboration with and supported by <a href="https://www.intel.com/content/www/us/en/research/overview.html" style="color: orange;">Intel Labs</a>.
      
      I possess strong hands-on experience with Python, Java, and cloud-based deployment of scalable solutions, along with a comprehensive understanding of machine learning libraries. I am deeply committed to leveraging AI to address complex, real-world challenges. My areas of interest include computer vision, time-series analytics, and natural language processing, with recent explorations into generative AI for healthcare diagnostics and industrial simulations. I also have peer-reviewed publications in these areas.

      I am always eager to connect, collaborate, and contribute to impactful AI-driven solutions. I’m actively seeking opportunities to collaborate on research and applied AI projects that drive meaningful impact.

    imageUrl: "home/propic.jpg"
    imageWidth: 220
    imageHeight: 220 
    buttons:
      - name: Resume
        url: "https://drive.google.com/file/d/1P_kww67S0AdRic_Hqi_JqdVsUkn3198i/view?usp=sharing"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:vvasa1@asu.edu"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/vasa-vamsi-krishna"
    - name: "github"
      url: "https://github.com/vasavamsi"
    - name: "google-scholar"
      url: "https://scholar.google.com/citations?hl=en&user=4-jHQiIAAAAJ"
      icon: "fa fa-google"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
      